version: '3'
services:
  network:
    image: openmined/grid-network:production
    build: ./apps/network
    environment:
      - PORT=7000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 7000:7000
  alice:
    image: unbiased/grid-node:demo
    build: ./apps/node
    environment:
      - NODE_ID=research_center2
      - ADDRESS=http://research_center2:5000/
      - PORT=5000
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5000:5000

  bob:
    image: unbiased/grid-node:demo
    build: ./apps/node
    environment:
      - NODE_ID=research_center1
      - ADDRESS=http://research_center1:5001/
      - PORT=5001
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5001:5001

  charlie:
    image: unbiased/grid-node:demo
    build: ./apps/node
    environment:
      - NODE_ID=Hospital_A
      - ADDRESS=http://Hospital_A:5002/
      - PORT=5002
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5002:5002
  dan:
    image: unbiased/grid-node:demo
    build: ./apps/node
    environment:
      - NODE_ID=Hospital_B
      - ADDRESS=http://Hospital_B:5003/
      - PORT=5003
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5003:5003

  jupyter:
    image: openmined/pysyft-notebook  # syft 0.2.9
    depends_on:
      - 'dan'
    ports:
      - 8888:8888
    volumes:
      - ./examples:/workspace/examples
